# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4d86dd36f205b9a913acc68204aff5d211113f9c2b918e6160d15561eadd44ddc8216c7a8c54252a91cebc64571e758aa40cc0df7eb147afbccf4f8c92abd81e

test:
  secret_key_base: a6fb8428360f083dc0f850a168683fa79537f1c6ec71e53c95a646b35ebbad6df37b86521f21842d297b264ddd53b32daa96f45013d1139aedbd16f5c478d75c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
